# Generated by Django 5.2 on 2025-04-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(default=3.5),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
