# Generated by Django 5.2 on 2025-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='property_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
