# Generated by Django 5.2 on 2025-04-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancellation_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='none', max_length=10),
        ),
    ]
